# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\coding\python\MyCloud\qt\UI\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1477, 915)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(50, 20, 1181, 51))
        self.widget.setObjectName("widget")
        self.minButton = QtWidgets.QPushButton(self.widget)
        self.minButton.setGeometry(QtCore.QRect(1090, 10, 41, 41))
        self.minButton.setText("")
        self.minButton.setObjectName("minButton")
        self.closeButton = QtWidgets.QPushButton(self.widget)
        self.closeButton.setGeometry(QtCore.QRect(1130, 10, 41, 41))
        self.closeButton.setText("")
        self.closeButton.setObjectName("closeButton")
        self.logo = QtWidgets.QLabel(self.widget)
        self.logo.setGeometry(QtCore.QRect(10, -20, 101, 101))
        self.logo.setText("")
        self.logo.setObjectName("logo")
        self.user_btn = QtWidgets.QPushButton(self.widget)
        self.user_btn.setGeometry(QtCore.QRect(970, 10, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.user_btn.setFont(font)
        self.user_btn.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.user_btn.setText("")
        self.user_btn.setObjectName("user_btn")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(50, 70, 211, 661))
        self.widget_2.setObjectName("widget_2")
        self.allfile_btn = QtWidgets.QPushButton(self.widget_2)
        self.allfile_btn.setGeometry(QtCore.QRect(0, 0, 211, 41))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(9)
        self.allfile_btn.setFont(font)
        self.allfile_btn.setObjectName("allfile_btn")
        self.doc_btn = QtWidgets.QPushButton(self.widget_2)
        self.doc_btn.setGeometry(QtCore.QRect(0, 40, 211, 41))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(9)
        self.doc_btn.setFont(font)
        self.doc_btn.setObjectName("doc_btn")
        self.img_btn = QtWidgets.QPushButton(self.widget_2)
        self.img_btn.setGeometry(QtCore.QRect(0, 80, 211, 41))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(9)
        self.img_btn.setFont(font)
        self.img_btn.setObjectName("img_btn")
        self.music_btn = QtWidgets.QPushButton(self.widget_2)
        self.music_btn.setGeometry(QtCore.QRect(0, 120, 211, 41))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(9)
        self.music_btn.setFont(font)
        self.music_btn.setObjectName("music_btn")
        self.video_btn = QtWidgets.QPushButton(self.widget_2)
        self.video_btn.setGeometry(QtCore.QRect(0, 160, 211, 41))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(9)
        self.video_btn.setFont(font)
        self.video_btn.setObjectName("video_btn")
        self.other_btn = QtWidgets.QPushButton(self.widget_2)
        self.other_btn.setGeometry(QtCore.QRect(0, 200, 211, 41))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(9)
        self.other_btn.setFont(font)
        self.other_btn.setObjectName("other_btn")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(260, 70, 971, 661))
        self.widget_3.setObjectName("widget_3")
        self.widget_4 = QtWidgets.QWidget(self.widget_3)
        self.widget_4.setGeometry(QtCore.QRect(20, 10, 931, 51))
        self.widget_4.setObjectName("widget_4")
        self.back_btn = QtWidgets.QPushButton(self.widget_4)
        self.back_btn.setGeometry(QtCore.QRect(10, 10, 31, 31))
        self.back_btn.setText("")
        self.back_btn.setObjectName("back_btn")
        self.forward_btn = QtWidgets.QPushButton(self.widget_4)
        self.forward_btn.setGeometry(QtCore.QRect(50, 10, 31, 31))
        self.forward_btn.setText("")
        self.forward_btn.setObjectName("forward_btn")
        self.refresh_btn = QtWidgets.QPushButton(self.widget_4)
        self.refresh_btn.setGeometry(QtCore.QRect(100, 10, 31, 31))
        self.refresh_btn.setText("")
        self.refresh_btn.setObjectName("refresh_btn")
        self.upload_btn = QtWidgets.QPushButton(self.widget_4)
        self.upload_btn.setGeometry(QtCore.QRect(190, 10, 91, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(9)
        self.upload_btn.setFont(font)
        self.upload_btn.setObjectName("upload_btn")
        self.mkdir_btn = QtWidgets.QPushButton(self.widget_4)
        self.mkdir_btn.setGeometry(QtCore.QRect(290, 10, 141, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(9)
        self.mkdir_btn.setFont(font)
        self.mkdir_btn.setObjectName("mkdir_btn")
        self.lineEdit = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit.setGeometry(QtCore.QRect(640, 10, 241, 31))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.search_btn = QtWidgets.QPushButton(self.widget_4)
        self.search_btn.setGeometry(QtCore.QRect(890, 10, 31, 31))
        self.search_btn.setText("")
        self.search_btn.setObjectName("search_btn")
        self.transfer_btn = QtWidgets.QPushButton(self.widget_4)
        self.transfer_btn.setGeometry(QtCore.QRect(480, 10, 111, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.transfer_btn.setFont(font)
        self.transfer_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.transfer_btn.setObjectName("transfer_btn")
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget_3)
        self.stackedWidget.setGeometry(QtCore.QRect(20, 70, 931, 581))
        self.stackedWidget.setObjectName("stackedWidget")
        self.allfile_page = QtWidgets.QWidget()
        self.allfile_page.setObjectName("allfile_page")
        self.allfile_table = QtWidgets.QTableWidget(self.allfile_page)
        self.allfile_table.setGeometry(QtCore.QRect(0, 0, 931, 581))
        self.allfile_table.setObjectName("allfile_table")
        self.allfile_table.setColumnCount(4)
        self.allfile_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.allfile_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.allfile_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.allfile_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.allfile_table.setHorizontalHeaderItem(3, item)
        self.stackedWidget.addWidget(self.allfile_page)
        self.doc_page = QtWidgets.QWidget()
        self.doc_page.setObjectName("doc_page")
        self.doc_table = QtWidgets.QTableWidget(self.doc_page)
        self.doc_table.setGeometry(QtCore.QRect(0, 0, 931, 581))
        self.doc_table.setObjectName("doc_table")
        self.doc_table.setColumnCount(4)
        self.doc_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.doc_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.doc_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.doc_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.doc_table.setHorizontalHeaderItem(3, item)
        self.stackedWidget.addWidget(self.doc_page)
        self.img_page = QtWidgets.QWidget()
        self.img_page.setObjectName("img_page")
        self.img_table = QtWidgets.QTableWidget(self.img_page)
        self.img_table.setGeometry(QtCore.QRect(0, 0, 931, 581))
        self.img_table.setObjectName("img_table")
        self.img_table.setColumnCount(4)
        self.img_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.img_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.img_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.img_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.img_table.setHorizontalHeaderItem(3, item)
        self.stackedWidget.addWidget(self.img_page)
        self.music_page = QtWidgets.QWidget()
        self.music_page.setObjectName("music_page")
        self.music_table = QtWidgets.QTableWidget(self.music_page)
        self.music_table.setGeometry(QtCore.QRect(0, 0, 931, 581))
        self.music_table.setObjectName("music_table")
        self.music_table.setColumnCount(4)
        self.music_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.music_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.music_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.music_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.music_table.setHorizontalHeaderItem(3, item)
        self.stackedWidget.addWidget(self.music_page)
        self.video_page = QtWidgets.QWidget()
        self.video_page.setObjectName("video_page")
        self.video_table = QtWidgets.QTableWidget(self.video_page)
        self.video_table.setGeometry(QtCore.QRect(0, 0, 931, 581))
        self.video_table.setObjectName("video_table")
        self.video_table.setColumnCount(4)
        self.video_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.video_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.video_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.video_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.video_table.setHorizontalHeaderItem(3, item)
        self.stackedWidget.addWidget(self.video_page)
        self.other_page = QtWidgets.QWidget()
        self.other_page.setObjectName("other_page")
        self.other_table = QtWidgets.QTableWidget(self.other_page)
        self.other_table.setGeometry(QtCore.QRect(0, 0, 931, 581))
        self.other_table.setObjectName("other_table")
        self.other_table.setColumnCount(4)
        self.other_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.other_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.other_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.other_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.other_table.setHorizontalHeaderItem(3, item)
        self.stackedWidget.addWidget(self.other_page)
        self.no_file_page = QtWidgets.QWidget()
        self.no_file_page.setObjectName("no_file_page")
        self.label_3 = QtWidgets.QLabel(self.no_file_page)
        self.label_3.setGeometry(QtCore.QRect(390, 190, 141, 121))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self.no_file_page)
        self.label_6.setGeometry(QtCore.QRect(340, 340, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.stackedWidget.addWidget(self.no_file_page)
        self.file_not_found_page = QtWidgets.QWidget()
        self.file_not_found_page.setObjectName("file_not_found_page")
        self.label_4 = QtWidgets.QLabel(self.file_not_found_page)
        self.label_4.setGeometry(QtCore.QRect(400, 190, 121, 121))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(self.file_not_found_page)
        self.label_7.setGeometry(QtCore.QRect(340, 340, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.stackedWidget.addWidget(self.file_not_found_page)
        self.search_result_page = QtWidgets.QWidget()
        self.search_result_page.setObjectName("search_result_page")
        self.search_table = QtWidgets.QTableWidget(self.search_result_page)
        self.search_table.setGeometry(QtCore.QRect(0, 0, 931, 581))
        self.search_table.setObjectName("search_table")
        self.search_table.setColumnCount(4)
        self.search_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.search_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.search_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.search_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.search_table.setHorizontalHeaderItem(3, item)
        self.stackedWidget.addWidget(self.search_result_page)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(8)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MyCloud"))
        self.allfile_btn.setText(_translate("MainWindow", "全部文件"))
        self.doc_btn.setText(_translate("MainWindow", "文档"))
        self.img_btn.setText(_translate("MainWindow", "图片"))
        self.music_btn.setText(_translate("MainWindow", "音乐"))
        self.video_btn.setText(_translate("MainWindow", "视频"))
        self.other_btn.setText(_translate("MainWindow", "其他"))
        self.upload_btn.setText(_translate("MainWindow", "上传"))
        self.mkdir_btn.setText(_translate("MainWindow", "新建文件夹"))
        self.transfer_btn.setText(_translate("MainWindow", "传输列表"))
        item = self.allfile_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "文件名"))
        item = self.allfile_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "大小"))
        item = self.allfile_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "修改时间"))
        item = self.allfile_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "操作"))
        item = self.doc_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "文件名"))
        item = self.doc_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "大小"))
        item = self.doc_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "修改时间"))
        item = self.doc_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "操作"))
        item = self.img_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "文件名"))
        item = self.img_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "大小"))
        item = self.img_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "修改时间"))
        item = self.img_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "操作"))
        item = self.music_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "文件名"))
        item = self.music_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "大小"))
        item = self.music_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "修改时间"))
        item = self.music_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "操作"))
        item = self.video_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "文件名"))
        item = self.video_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "大小"))
        item = self.video_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "修改时间"))
        item = self.video_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "操作"))
        item = self.other_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "文件名"))
        item = self.other_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "大小"))
        item = self.other_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "修改时间"))
        item = self.other_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "操作"))
        self.label_6.setText(_translate("MainWindow", "当前没有文件哦，快来上传吧"))
        self.label_7.setText(_translate("MainWindow", "没有搜索到相关文件"))
        item = self.search_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "文件名"))
        item = self.search_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "大小"))
        item = self.search_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "修改时间"))
        item = self.search_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "操作"))
