# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\coding\python\MyCloud\qt\UI\share_link.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ShareLinkWindow(object):
    def setupUi(self, ShareLinkWindow):
        ShareLinkWindow.setObjectName("ShareLinkWindow")
        ShareLinkWindow.resize(599, 481)
        self.centralwidget = QtWidgets.QWidget(ShareLinkWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 50, 421, 361))
        self.widget.setObjectName("widget")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 300, 141, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(40, 40, 111, 231))
        self.widget_2.setObjectName("widget_2")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setGeometry(QtCore.QRect(0, 10, 99, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(0, 50, 99, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(0, 140, 99, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.pwd_label = QtWidgets.QLabel(self.widget)
        self.pwd_label.setGeometry(QtCore.QRect(170, 90, 231, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(10)
        self.pwd_label.setFont(font)
        self.pwd_label.setText("")
        self.pwd_label.setAlignment(QtCore.Qt.AlignCenter)
        self.pwd_label.setObjectName("pwd_label")
        self.qr_label = QtWidgets.QLabel(self.widget)
        self.qr_label.setGeometry(QtCore.QRect(220, 130, 141, 141))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(10)
        self.qr_label.setFont(font)
        self.qr_label.setText("")
        self.qr_label.setAlignment(QtCore.Qt.AlignCenter)
        self.qr_label.setObjectName("qr_label")
        self.link_label = QtWidgets.QLineEdit(self.widget)
        self.link_label.setGeometry(QtCore.QRect(170, 50, 231, 31))
        self.link_label.setObjectName("link_label")
        self.widget_2.raise_()
        self.pushButton_2.raise_()
        self.pwd_label.raise_()
        self.qr_label.raise_()
        self.link_label.raise_()
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(10, 10, 421, 41))
        self.widget_3.setObjectName("widget_3")
        self.minButton = QtWidgets.QPushButton(self.widget_3)
        self.minButton.setGeometry(QtCore.QRect(330, 0, 41, 41))
        self.minButton.setText("")
        self.minButton.setObjectName("minButton")
        self.closeButton = QtWidgets.QPushButton(self.widget_3)
        self.closeButton.setGeometry(QtCore.QRect(370, 0, 41, 41))
        self.closeButton.setText("")
        self.closeButton.setObjectName("closeButton")
        self.label_7 = QtWidgets.QLabel(self.widget_3)
        self.label_7.setGeometry(QtCore.QRect(0, 0, 101, 41))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        ShareLinkWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ShareLinkWindow)
        QtCore.QMetaObject.connectSlotsByName(ShareLinkWindow)

    def retranslateUi(self, ShareLinkWindow):
        _translate = QtCore.QCoreApplication.translate
        ShareLinkWindow.setWindowTitle(_translate("ShareLinkWindow", "分享链接"))
        self.pushButton_2.setText(_translate("ShareLinkWindow", "复制分享链接"))
        self.label.setText(_translate("ShareLinkWindow", "分享链接"))
        self.label_2.setText(_translate("ShareLinkWindow", "分享密码"))
        self.label_3.setText(_translate("ShareLinkWindow", "二维码"))
        self.label_7.setText(_translate("ShareLinkWindow", "分享链接"))
